version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
  - package-ecosystem: "gradle"
    directory: "/packages/react-native-mmkv/android/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
