name: Harness iOS

on:
  workflow_dispatch:
    inputs:
      device_model:
        description: "iOS Simulator device model"
        required: false
        default: "iPhone 16 Pro"
        type: string
      ios_version:
        description: "iOS version"
        required: false
        default: "18.6"
        type: string
  workflow_run:
    workflows: ["Build iOS"]
    types:
      - completed

env:
  # Device configuration - can be overridden by workflow_dispatch inputs
  DEVICE_MODEL: ${{ github.event.inputs.device_model || 'iPhone 16 Pro' }}
  IOS_VERSION: ${{ github.event.inputs.ios_version || '18.6' }}

jobs:
  harness_ios_new:
    name: Harness iOS (new architecture)
    runs-on: macos-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2

      - name: Install npm dependencies (bun)
        run: bun install

      - name: Download iOS app artifact
        uses: actions/download-artifact@v4
        with:
          name: ios-app
          path: example/ios/build/Build/Products/Debug-iphonesimulator/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Setup iOS Simulator
        uses: futureware-tech/simulator-action@v4
        with:
          model: ${{ env.DEVICE_MODEL }}
          os: iOS
          os_version: ${{ env.IOS_VERSION }}
          wait_for_boot: true
          erase_before_boot: false

      - name: Install app
        run: |
          xcrun simctl install booted example/ios/build/Build/Products/Debug-iphonesimulator/MmkvExample.app

      - name: Run Harness E2E tests
        working-directory: example
        continue-on-error: true
        run: |
          bun react-native-harness test ios
